### ISSUE TITLE
Incorrect extender port value passed in csi-deployment chart

### ISSUE THREAD

**Issue by safronovD** [dell/csi-baremetal#423]
schedulerpatcher-config:
```
policy.yaml:
----
apiVersion: v1
kind: Policy
extenders:
  - urlPrefix: "http://127.0.0.1:"
    filterVerb: filter
    prioritizeVerb: prioritize
    weight: 1
    #bindVerb: bind
    enableHttps: false
    nodeCacheCapable: false
    ignorable: true
    # 15 seconds
    httpTimeout: 15000000000
```

`{{ .Values.scheduler.extender_port }}` is incorrect
